sudo:required
services:
  - docker

before_install:
  - docker build -t Hemantkunder2422/docker-react -f Dockerfile.dev .  


script:
  - docker run Hemantkunder2422/docker-react npm run test -- --coverage
